--- #YAML:1.0
name:               Chess-Rep
version:            0.6
abstract:           represent chess positions, generate list of legal moves, parse moves in various formats.
author:
    - Mihai Bazon <mihai.bazon@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
